version: '3.9'

services:
  postgres:
    image: postgres
    container_name: bus_reservation_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bus_reservation
    ports:
      - "5432:5432"
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

